import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const deliusSwashCaps = localFont({
  src:"./fonts/DeliusSwashCaps-Regular.ttf",
  variable: "--font-delius-swash-caps",
  weight: "400"
});
const playfairDisplay=localFont({
  src:[
    { path: "./fonts/PlayfairDisplay-Black.ttf" },
    { path: "./fonts/PlayfairDisplay-BlackItalic.ttf" },
    { path: "./fonts/PlayfairDisplay-Bold.ttf" },
    { path: "./fonts/PlayfairDisplay-BoldItalic.ttf" },
    { path: "./fonts/PlayfairDisplay-ExtraBold.ttf" },
    { path: "./fonts/PlayfairDisplay-ExtraBoldItalic.ttf" },
    { path: "./fonts/PlayfairDisplay-Italic.ttf" },
    { path: "./fonts/PlayfairDisplay-Medium.ttf" },
    { path: "./fonts/PlayfairDisplay-MediumItalic.ttf" },
    { path: "./fonts/PlayfairDisplay-Regular.ttf" },
    { path: "./fonts/PlayfairDisplay-SemiBold.ttf" },
    { path: "./fonts/PlayfairDisplay-SemiBoldItalic.ttf" }
  ],
  variable: "--font-playfair-display"
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${playfairDisplay.variable} ${deliusSwashCaps.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
